# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 482dbe3bf9c1ae73789203a96ae361c8e74608fad5c5669fb2d109045582b86d6dcaeaf875000f2629ff971d387c5b9237b92fc4747566e3dca2dc0a00a562a8

test:
  secret_key_base: 121be3942f0dfe740a32db9078ffb76ac2173c8775d2ad4a269025c09837433e341b629ff35719c30868756d5a3831d1b11c45df2fe484cb6596cbfb3687bf3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
